language: python

python:
  - 3.6
  - 2.7
  - 3.5

env:
  - TOXENV=py,codecov-travis OMPI_CC=/usr/bin/gcc-6 OMPI_CXX=/usr/bin/g++-6
  - TOXENV=py-pythran,codecov-travis OMPI_CC=/usr/bin/gcc-6 OMPI_CXX=/usr/bin/g++-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - libfftw3-dev
      - libfftw3-mpi-dev
      - libhdf5-openmpi-dev
      - openmpi-bin
      - libopenblas-dev

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=lint
      addons:
        # workaround because of the pip install -U ... mpi4py line in install section
        apt:
          packages: [libopenmpi-dev, openmpi-bin]

  allow_failures:
    - python: 3.6
      env: TOXENV=lint

  exclude:
    - python: 3.5
      env: TOXENV=py,codecov-travis OMPI_CC=/usr/bin/gcc-6 OMPI_CXX=/usr/bin/g++-6

before_cache:
  - |
      coverage erase
      rm -f $HOME/.cache/pip/log/debug.log

cache:
    directories:
        - $HOME/.cache/pip
        # - $TRAVIS_BUILD_DIR/.tox

install:
    - pip install -U pip "setuptools<=36.6.0" wheel six colorlog
    - pip install -U tox-pipenv coverage
    - pip install -U numpy cython mako mpi4py  # To be removed when pip==10 is out and this step can be bootstrapped

before_script:
    - |
      mkdir -p $HOME/.config/matplotlib
      echo 'backend      : agg' > $HOME/.config/matplotlib/matplotlibrc
      echo '[pythran]\ncomplex_hook = True' > $HOME/.pythranrc
      wget https://bitbucket.org/fluiddyn/fluidfft/raw/default/site.cfg.files/site.cfg.travis -O $HOME/.fluidfft-site.cfg

script:
    - travis_wait 30 tox -vv

notifications:
  email: false
  irc: "chat.freenode.net#fluiddyn-dev"
