
channels:
  - conda-forge

dependencies:
  - python=3.6
  - pandas
  - cython
  - h5py
  - jupyter
  - matplotlib
  - fftw
  - pyfftw
  - mako
  - pip:
    - sphinx
    - numpydoc
    - sphinx_rtd_theme
    - hg+https://bitbucket.org/fluiddyn/fluiddyn#egg=fluiddyn
    - hg+https://bitbucket.org/fluiddyn/fluidfft#egg=fluidfft
