
channels:
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - cython
  - h5py
  - sphinx
  - numpydoc
  - jupyter
  - matplotlib
  - fftw
  - pyfftw
  - mako
  - pip:
    - sphinx_rtd_theme
    - fluidfft
