
channels:
  - conda-forge

dependencies:
  - python=3.6
  - scipy
  - pandas
  - cython
  - h5py
  - sphinx
  - numpydoc
  - jupyter
  - matplotlib
  - fftw
  - pyfftw
  - mako
  - pip:
    - sphinx_rtd_theme
    - hg+https://bitbucket.org/fluiddyn/fluiddyn#egg=fluiddyn
    - hg+https://bitbucket.org/fluiddyn/fluidfft#egg=fluidfft
